# This is a basic workflow to help you get started with Actions

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [ 11, 15 ]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v2.1.0
        with: 
          java-version: ${{ matrix.java-version }}
          distribution: adopt
          
      - name: Maven compilation
        run: mvn -T 1C clean generate-sources compile --file pom.xml
        
  test:
    runs-on: ubuntu-latest
    needs: [build]
    
    strategy:
      matrix:
        java-version: [ 11, 15 ]
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK for tests
        uses: actions/setup-java@v2.1.0
        with: 
          java-version: ${{ matrix.java-version }}
          distribution: adopt
          
      - name: Maven tests
        run: mvn -T 1C test-compile test --file pom.xml

  analisys:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment: SonarCloud
    
    steps:
      - name: SonarCloud analisys
        uses: SonarSource/sonarcloud-github-action@v1.6
